coinbase/cadence-ruby

lib/cadence/version.rb
lib/cadence/workflow/serializer/start_timer.rb

When supplied with anything other than Integer it will fail to serialize a Thrift message

[Fix] Cast StartTimer timeout to Integer

---

lib/cadence/testing/local_workflow_context.rb
lib/cadence/version.rb

Add sleep_until to local workflow context

---

lib/cadence.rb
spec/unit/lib/cadence_spec.rb

It does not seem practical to raise this error, especially when registering domain on every deploy (ensuring it's present)

Ignore DomainAlreadyExistsError when registering domain

---

lib/cadence/testing/local_workflow_context.rb
lib/cadence/version.rb
spec/unit/lib/cadence/utils_spec.rb
spec/unit/lib/cadence/workflow/context_spec.rb
spec/unit/lib/cadence_spec.rb

Some specs were broken so I cleaned those up.
The Cadence::Testing wasn't passing timeouts in to the Activity metadata causing tests to fail. Passed in some dummy values to allow it to work.
bumped version

Fix specs, fix cadence testing timeout issue, bump version to 0.0.1-pre43

---

lib/cadence/activity/poller.rb
lib/cadence/activity/task_processor.rb
lib/cadence/thread_pool.rb
lib/cadence/version.rb
lib/cadence/worker.rb
lib/cadence/workflow/poller.rb
spec/unit/lib/cadence/activity/poller_spec.rb

A couple of improvements:
1. Make sure threads survive exceptions raised in Activities
2. Log any unhandled exceptions for debugging purposes
3. Make sure to stop all the thread pool threads when shutting down the worker

Improve worker's reliability

---

lib/cadence/client/thrift_client.rb
lib/cadence/version.rb
spec/unit/lib/cadence_spec.rb

Without a provided `requestId` a workflow be only be reset once making all subsequent calls idempotent. This is not the expected behaviour for most part since it is useful to be able to reset a workflow multiple times.

[Fix] Add requestId to reset_workflow_execution call

---

lib/cadence/errors.rb
lib/cadence/workflow/decision_task_processor.rb
lib/cadence/workflow/history/event_target.rb
lib/cadence/workflow/state_manager.rb

This change will ensure that when a workflow is replayed all the decision match previously made ones and will raise `Cadence:: NonDeterministicWorkflowError` if not

Implement workflow determinism check

---

examples/bin/worker
lib/cadence/activity/poller.rb
lib/cadence/client.rb
lib/cadence/client/thrift_client.rb
lib/cadence/worker.rb
lib/cadence/workflow/poller.rb
spec/unit/lib/cadence/activity/poller_spec.rb
spec/unit/lib/cadence/worker_spec.rb

This will allow some extra flexibility when configuring the worker. Namely adding 2 options:
- `polling_ttl` — How long a poller should keep the connection option waiting for a task, specified in seconds
- `thread_pool_size` — How many thread a worker should use when processing activity tasks. Basically controls concurrency

Make polling TTL and thread pools configurable

---

lib/cadence.rb
lib/cadence/client/thrift_client.rb
spec/unit/lib/cadence_spec.rb

Exposing an API call for workflow termination. This call will immediately stop workflow execution halting any running activities, timers, etc.

[Feature] Add workflow termination call

---

lib/cadence/client/thrift_client.rb
lib/cadence/version.rb
lib/cadence/workflow/decision_task_processor.rb
spec/fabricators/thrift/decision_task_fabricator.rb
spec/fabricators/thrift/history_event_fabricator.rb
spec/fabricators/thrift/history_fabricator.rb
spec/fabricators/thrift/task_list_fabricator.rb
spec/fabricators/thrift/workflow_execution_history_fabricator.rb
spec/unit/lib/cadence/workflow/decision_task_processor_spec.rb

Cadence paginates history when it becomes too big, this PR enables the gem to prefetch all of it before processing a decision task.
Also added a full spec for DecisionTaskProcessor along with this a spec for this change

Add support for paginated workflow history

---

lib/cadence/activity/poller.rb
lib/cadence/workflow/poller.rb
spec/unit/lib/cadence/activity/poller_spec.rb
spec/unit/lib/cadence/workflow/poller_spec.rb

This new metric will help detect resource contention on Cadence workers. Increased time between polls indicates thread unavailability (in case of activity poller) and slow decision processing (for the workflow poller)

[Feature] Report time between poller loops

---

CHANGELOG.md
lib/cadence/version.rb
lib/cadence/workflow/poller.rb
spec/unit/lib/cadence/activity/poller_spec.rb
spec/unit/lib/cadence/workflow/poller_spec.rb

After heavy load-testing it looks like workflow workers spend most of their time communicating results back to Cadence. Previously it was assumed that they are CPU-bound so thread pooling would not bring any benefits. But since this is not necessarily the case, thread pooling will allow running less workflow workers to sustain the same decision task throughput.

[Feature] Add thread pool support to the workflow poller

---

lib/cadence.rb
lib/cadence/activity/context.rb
lib/cadence/activity/poller.rb
lib/cadence/activity/task_processor.rb
lib/cadence/configuration.rb
lib/cadence/connection.rb
lib/cadence/connection/errors.rb
lib/cadence/connection/thrift.rb
lib/cadence/execution_options.rb
lib/cadence/worker.rb
lib/cadence/workflow/context.rb
lib/cadence/workflow/decision_task_processor.rb
lib/cadence/workflow/executor.rb
lib/cadence/workflow/poller.rb
spec/unit/lib/cadence/activity/context_spec.rb
spec/unit/lib/cadence/activity/poller_spec.rb
spec/unit/lib/cadence/activity/task_processor_spec.rb
spec/unit/lib/cadence/testing_spec.rb
spec/unit/lib/cadence/worker_spec.rb
spec/unit/lib/cadence/workflow/context_spec.rb
spec/unit/lib/cadence/workflow/decision_task_processor_spec.rb
spec/unit/lib/cadence/workflow/poller_spec.rb
spec/unit/lib/cadence_spec.rb

I'm working on a bigger change that will turn Cadence into an initializable class rather than using a single global instance. This will allow connecting your app to multiple clusters (this is handy for easy migrating from one Cadence cluster to another or more exotic solutions such as client-side sharding).
This is the first step which makes configuration local, passed to all classes that are using it

[Refactor] Use local configuration instead of a global one

---

lib/cadence.rb
lib/cadence/client.rb
lib/cadence/testing.rb
spec/unit/lib/cadence/client_spec.rb
spec/unit/lib/cadence/testing_spec.rb
spec/unit/lib/cadence_spec.rb

This turns `Cadence` into an initializable `Cadence::Client` allowing to connect to multiple clusters:
```
config_1 = Cadence::Configuration.new
config_1.host = 'xxx'
client_1 = Cadence::Client.new(config_1)
client_1.start_workflow(TestWorkflow)
config_2 = Cadence::Configuration.new
config_2.host = 'xxx'
client_2 = Cadence::Client.new(config_2)
client_2.start_workflow(TestWorkflow)
```
This change is backwards compatible and `Cadence.*` class methods are simply delegated to a default client.
The "meat" of this PR is moving `Cadence` methods into `Cadence::Client` and moving specs

[Feature] Initializable Cadence client

---

CONTRIBUTING.md
README.md
examples/README.md
proxy/README.md

This fixes a couple spelling mistakes and a broken link.  It also removes the [not yet implemented] note for child workflows from the README as it looks like they were implemented with #7 .

Fix documentation spelling and broken link

---

CHANGELOG.md
lib/cadence/concerns/executable.rb
lib/cadence/execution_options.rb
lib/cadence/version.rb
spec/shared_examples/an_executable.rb
spec/unit/lib/cadence/execution_options_spec.rb

This PR will make retry_policy passed via options mergeable with the retry_policy specified in the Executable class:
```ruby
class TestActivity < Cadence::Activity
class TestError < StandardError; end
retry_policy interval: 1, backoff: 2, max_attempt: 10, non_retriable_errors: [TestError]
end
```
then in a workflow:
```ruby
TestActivity.execute!(options: { retry_policy: { interval: 2, backoff: 3 } })
```
This will partially override activity's retry policy with the explicitly passed options, resulting in `interval: 2, backoff: 3, max_attempt: 10, non_retriable_errors: [TestError]`.
It also fixes a bug with retry_policy passed as options, which didn't work previously. The full set of specs for the ExecutionOptions has been added.

[Feature] Make retry_policy mergeable

---

CHANGELOG.md
lib/cadence/client.rb
lib/cadence/reset_strategy.rb
lib/cadence/version.rb
lib/cadence/workflow/history.rb
spec/fabricators/thrift/history_event_fabricator.rb
spec/unit/lib/cadence/client_spec.rb
spec/unit/lib/cadence/workflow/history_spec.rb

This change would allow specifying a strategy when resetting a workflow. This is very useful when resetting a batch of workflows that all might have failed at different points in history
Tested against a running server & specs updated to reflect the change

[Feature] Strategies for resetting workflows

---

lib/cadence/metadata/activity.rb
lib/cadence/metadata/base.rb
lib/cadence/metadata/decision.rb
lib/cadence/metadata/workflow.rb
spec/unit/lib/cadence/metadata/activity_spec.rb
spec/unit/lib/cadence/metadata/decision_spec.rb
spec/unit/lib/cadence/metadata/workflow_spec.rb

Synced from https://github.com/coinbase/temporal-ruby/pull/44
This will allow for uniform metadata logging (added separately)

Add Metadata::Base#to_h

---

lib/cadence/workflow/history/event.rb
lib/cadence/workflow/history/event_target.rb
lib/cadence/workflow/state_manager.rb
spec/fabricators/thrift/history_event_fabricator.rb
spec/unit/lib/cadence/workflow/history/event_spec.rb
spec/unit/lib/cadence/workflow/history/event_target_spec.rb

Fixes a bug described in https://github.com/coinbase/temporal-ruby/issues/75
The non-determinism check depends on the class `EventTarget` that creates a canonical event that is used when matching commands to history events (schedule_activity -> activity_scheduled, etc). This allows to check the pending command (not yet sent to Temporal) and history events and remove the ones that are already in the history (in the same order as they were scheduled).
There were 2 bugs with this:
1. When creating an `EventTarget` from an event we did a prefix match favouring the first match. This means that between `ActivityTask` and `ActivityTaskCancel` the first one would win and will generate an incorrect event target (activity, instead of cancel_activity). Fixed by matching all and picking the last …

[Fix] Correctly handle timer/activity cancelation events

---

CHANGELOG.md
examples/activities/async_activity.rb
examples/bin/worker
examples/spec/integration/async_activity_workflow_spec.rb
examples/spec/integration/async_timer_workflow_spec.rb
examples/spec/integration/cancelling_timer_workflow_spec.rb
examples/workflows/async_timer_workflow.rb
lib/cadence/testing/cadence_override.rb
lib/cadence/testing/future_registry.rb
lib/cadence/testing/local_workflow_context.rb
lib/cadence/testing/workflow_execution.rb
lib/cadence/version.rb

This PR implements all the required capabilities to test async timers. Right now these are not actually counting the time (which would be really difficult to test), however can be fired off manually when needed. Any set callback will also get executed.
The timer can be fired off using a new (testing-only) API — `Cadence.fire_timer`
Tested with new unit and integration specs

[Feature] Enable timer operations in testing mode

---

CHANGELOG.md
lib/cadence/version.rb
lib/cadence/workflow/history/event.rb
spec/unit/lib/cadence/workflow/history/event_spec.rb

#56 has introduced a regression which would associate timer cancelation request with the timer itself resulting in a non-deterministic replay (attempting to match timer's cancellation with initiation of the timer, which are two separate commands).
It was tested using a sample workflow and a unit spec

Fix timer cancellation regression

---

CHANGELOG.md
lib/cadence/metadata.rb
lib/cadence/metadata/workflow.rb
lib/cadence/testing/cadence_override.rb
lib/cadence/testing/workflow_override.rb
lib/cadence/version.rb
lib/cadence/workflow/decision_task_processor.rb
lib/cadence/workflow/executor.rb
lib/cadence/workflow/state_manager.rb
spec/fabricators/workflow_metadata_fabricator.rb
spec/unit/lib/cadence/activity/task_processor_spec.rb
spec/unit/lib/cadence/metadata/workflow_spec.rb
spec/unit/lib/cadence/metadata_spec.rb
spec/unit/lib/cadence/workflow/context_spec.rb
spec/unit/lib/cadence/workflow/decision_task_processor_spec.rb
spec/unit/lib/cadence/workflow/executor_spec.rb

There are 3 types of metadata — decision, activity and workflow. Each is exposed to different parts of the SDK.
Workflow ID is generated from the history, which confusingly doesn't have domain or workflow_id. This PR adds these 2 missing fields from the decision metadata
Tested using unit specs and manual workflow runs

[Feature] Add id and domain to workflow context's metadata

---

CHANGELOG.md
examples/bin/worker
lib/cadence/crew.rb
lib/cadence/version.rb
spec/unit/lib/cadence/crew_spec.rb

Because of the limitations Ruby has with multi-threading we find ourselves starting up multiple worker processes on our instances.  Currently we manage this with docker containers and lots of copy-paste.
This PR adds the notion of a "crew" of workers. When a crew is dispatched it simply forks the worker given `n` times and relays any TERM or INT signals given to all child processes.

Add a Crew implementation

---

examples/bin/crew
examples/bin/worker
lib/cadence/crew.rb
rbi/cadence-ruby.rbi
spec/unit/lib/cadence/crew_spec.rb

We ran into [this issue](https://github.com/grpc/grpc/issues/7951) when attempting to roll out the crew feature. To work around that we'll need to initialize all of our workflows and activities in the forked process instead of the main process. So this PR adds an `after_fork` block that we can set to do that initialization.
automerge=true

Add an after_fork hook to the crew class

---

examples/bin/trigger
examples/bin/worker
examples/middleware/sample_propagator.rb
lib/cadence/client.rb
lib/cadence/configuration.rb
lib/cadence/middleware/header_propagator_chain.rb
lib/cadence/worker.rb
lib/cadence/workflow/context.rb
lib/cadence/workflow/decision_task_processor.rb
lib/cadence/workflow/executor.rb
lib/cadence/workflow/poller.rb
spec/unit/lib/cadence/client_spec.rb
spec/unit/lib/cadence/middleware/header_propagator_chain_spec.rb
spec/unit/lib/cadence/worker_spec.rb
spec/unit/lib/cadence/workflow/decision_task_processor_spec.rb
spec/unit/lib/cadence/workflow/executor_spec.rb
spec/unit/lib/cadence/workflow/poller_spec.rb

This change contains the following changes, and closely mirrors https://github.com/coinbase/temporal-ruby/pull/226.
1. Workflow middleware
This is configured on a worker similar to workflow_task and acitvity middleware (worker.add_workflow_middleware(middleware). Workflow middleware gets the workflow metadata which contains headers, and can be used to extract things out of the headers. Activities already have this support via the activity middleware.
2. Header propagation (inject into outgoing headers)
This is configured on the temporal configuration (c.add_header_propagator(propagator)). The propagator is for outgoing headers- so you want to inject into the headers. A propagator is just a class that implements def inject!(header) that modifies header in place and does not return …

Add header propagation and workflow middleware.

---

CHANGELOG.md
lib/cadence/metadata/workflow.rb
lib/cadence/version.rb
lib/cadence/workflow/executor.rb
spec/fabricators/thrift/history_event_fabricator.rb
spec/fabricators/workflow_metadata_fabricator.rb
spec/unit/lib/cadence/metadata/workflow_spec.rb
spec/unit/lib/cadence/workflow/executor_spec.rb

**What changed**
This change exposes the parent workflow info, specifically the workflow id and run id, in the Cadence::Metadata::Workflow object so that it is accessible within a child workflow. This is only present if there is actually a parent workflow, nil otherwise.
For reference, this was added a whiles back to cadence thrift as a property in the `workflowExecutionStartedEventAttributes` event, and then supported in the go and java clients, see https://github.com/uber/cadence/issues/540
**Tests**
This is tested via rspec - existing specs to ensure status quo is unchanged, and new specs .

Expose parent workflow info (ID and RunID) in Cadence::Metadata::Workflow object

---

CHANGELOG.md
lib/cadence/client.rb
lib/cadence/version.rb
rbi/cadence-ruby.rbi
spec/unit/lib/cadence/client_spec.rb

This change modifies the parameter requirement from `workflow` to `domain` in a new method signal_workflow_execution. There is no reason for workflow to be passed in just to get the domain, and the `workflow` object is not accessible from within the workflow.

Pass in domain rather than workflow for new method signal workflow execution

---

.github/workflows/tests.yml
spec/unit/lib/cadence/crew_spec.rb
spec/unit/lib/cadence/worker_spec.rb

This runs our basic (unit) specs in a github actions workflow for all PRs.
Our CircleCI integration broke a while ago and tests were no longer running in PRs. 
I haven't gotten the examples (integration) specs working yet, they seem to be broken locally and in github actions, so they aren't included in this PR.

Run basic specs in a github actions workflow

---

CHANGELOG.md
lib/cadence/version.rb
lib/cadence/workflow/history/event.rb
lib/cadence/workflow/history/event_target.rb
lib/cadence/workflow/state_manager.rb
spec/fabricators/thrift/history_event_fabricator.rb
spec/unit/lib/cadence/workflow/history/event_spec.rb
spec/unit/lib/cadence/workflow/history/event_target_spec.rb
spec/unit/lib/cadence/workflow/state_manager_spec.rb

**Why**
* `StateManager` verify a workflow determinism by comparing the `EventTarget` from history events and the one generated from workflow logic. 
* `EventTarget` only contains `decision_id` and `type`
* `type` differentiates whether the decision is for scheduling an activity or fire a timer. 
* It does not contain extra attributes like activity type and inputs. 
* As a result, `StateManager` cannot detect indeterminism between two different activities. 
**Whats Changed**
* Consolidate `EventTarget` construction logics to the same file. 
* Include activity id, type and input attributes as part of the `EventTarget` equality. 
* If the `EventTarget` from history event is different from the `EventTarget` from the current decision, `StateManager` raise `NonDeterministicWorkflowError`. …

Check activity id, type and input to detect non-deterministic workflow when applying history

---

CHANGELOG.md
lib/cadence/activity/task_processor.rb
lib/cadence/version.rb
lib/cadence/workflow/decision_task_processor.rb
spec/unit/lib/cadence/workflow/decision_task_processor_spec.rb

**Why**
The current Cadence logs do not identify the exact instance of workflow and activity that's being processed or raising exceptions. Diagnostic and remediation based on these logs are hard. 
**What's changed**
* Add `workflow_id` to info and above logs in `Cadence::Workflow::DecisionTaskProcessor`
* Add `activity_id`, `workflow_name` and `workflow_id` to info and above logs in `Cadence::Activity::TaskProcessor`
**Testing**

Add workflow id and activity id to workflow and activity logs

---

lib/cadence/saga/saga.rb
rbi/cadence-ruby.rbi
spec/unit/lib/cadence/saga/concern_spec.rb
spec/unit/lib/cadence/saga/saga_spec.rb

More fixes for ruby3 compatibility. I missed these in https://github.com/coinbase/cadence-ruby/pull/91.

Fixes for ruby 3 compatibility

---

rbi/cadence-ruby.rbi

Add WorkflowAlreadyCompletingError to the rbi file - followup from https://github.com/coinbase/cadence-ruby/pull/93

Add WorkflowAlreadyCompletingError to the rbi file
